export { default as profile2 } from './profile2.jpg'
export { default as profile4 } from './profile4.jpg'
export { default as profile5 } from './profile5.jpg'
export { default as profile6 } from './profile6.jpg'
export { default as profile7 } from './profile7.jpg'